name: Deploy to IPFS

on:
    push:
        branches:
            - main
        paths:
            - "nft-site/**"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Deploy to IPFS
              uses: aquiladev/ipfs-action@v0.3.1
              with:
                  path: "./nft-site"
                  service: "pinata"
                  pinataKey: ${{ secrets.PINATA_API_KEY }}
                  pinataSecret: ${{ secrets.PINATA_SECRET_API_KEY }}
